/*
 * Copyright (c) 2018 Christian Taedcke, Diego Sueiro
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __INC_BOARD_H
#define __INC_BOARD_H

#ifdef __cplusplus
extern "C" {
#endif

#ifndef _ASMLANGUAGE

#include <soc.h>

#endif /* !_ASMLANGUAGE */


#define EFR32MG_SLTB004A_IMU_ENABLE_PORT        CONFIG_GPIO_GECKO_PORTF_NAME
#define EFR32MG_SLTB004A_IMU_ENABLE_PIN         8

#define EFR32MG_SLTB004A_ENV_SENSE_ENABLE_PORT  CONFIG_GPIO_GECKO_PORTF_NAME
#define EFR32MG_SLTB004A_ENV_SENSE_ENABLE_PIN   9

#define EFR32MG_SLTB004A_MIC_ENABLE_PORT        CONFIG_GPIO_GECKO_PORTF_NAME
#define EFR32MG_SLTB004A_MIC_ENABLE_PIN         10

#define EFR32MG_SLTB004A_CCS811_ENABLE_PORT     CONFIG_GPIO_GECKO_PORTF_NAME
#define EFR32MG_SLTB004A_CCS811_ENABLE_PIN      14

#define EFR32MG_SLTB004A_HALL_ENABLE_PORT       CONFIG_GPIO_GECKO_PORTB_NAME
#define EFR32MG_SLTB004A_HALL_ENABLE_PIN        10

#ifdef __cplusplus
}
#endif

#endif /* __INC_BOARD_H */
